
#define CHECK(BOOL, FUNCTION_NAME, OTHER_DATA, TYPE) (check (BOOL) (TYPE) (FUNCTION_NAME) __LINE__ __FILE__ (OTHER_DATA))

#ifdef FTENSOR_BOUNDS_CHECKS
#define BOUNDS_CHECK(BOOL, FUNCTION_NAME, OTHER_DATA) CHECK(BOOL, FUNCTION_NAME, OTHER_DATA, "bounds")
#else
#define BOUNDS_CHECK(BOOL, FUNCTION_NAME, TYPE) (Prelude.id)
#endif

#ifdef FTENSOR_UNSAFE_CHECKS
#define UNSAFE_CHECK(BOOL, FUNCTION_NAME, OTHER_DATA) CHECK(BOOL, FUNCTION_NAME, OTHER_DATA, "unsafe")
#else
#define UNSAFE_CHECK(BOOL, FUNCTION_NAME, TYPE) (Prelude.id)
#endif

#ifdef FTENSOR_INTERNAL_CHECKS
#define INTERNAL_CHECK(BOOL, FUNCTION_NAME, OTHER_DATA) CHECK(BOOL, FUNCTION_NAME, OTHER_DATA, "internal")
#else
#define INTERNAL_CHECK(BOOL, FUNCTION_NAME, TYPE) (Prelude.id)
#endif

